### ISSUE TITLE
Historical Decomposition of Shocks 

### ISSUE THREAD

**Issue by as4456** [chrstdanne/VARsignR#1]
Hi Christian,
I am currently going through this paper "Understanding the turbulence in financial markets"
mentioned here:
https://docs.google.com/viewer?a=v&pid=sites&srcid=ZGVmYXVsdGRvbWFpbnxqdWFuYW50b2xpbmRpYXp8Z3g6MjA1NDgzYWVhYTc1ODI5MA
and trying to implement the SVAR model explained in Page 7 with 4 structural shocks to these 4 endogenous variables. The imposed sign restriction on IRFS of the endogenous vars is given in Table 1 (page 8). The model is estimated using BVAR estimation using Minnesota prior.

I am trying to estimate this model using your package and have certain doubts:
In your example using uhligdata, when constructing the sign restriction vector, you have stated that
first element of constr indicates the shock of interest in the model. 

In your example this shock is due to an endogenous variable (interest rate). In my example how do I give this shock of interest of an exogenous shock (like monetary policy,agg demand,agg supply,risk aversion etc.).

Also how do I construct the historical decomposition of shocks explained in page 12.

If we want to plot the historical decomposition of shocks, where the shocks are due to all endogenous variables, we can use this approach
https://stackoverflow.com/questions/36950491/historical-decomposition-in-r
Here the shocks are exogenous.

I would really appreciate if you could help me in clearing these doubts.

Thanks

**Comment by chrstdanne** [comment]
Hi Amandeep, 
The package cannot estimate this type of model, since it does not allow for Minnesota-style Priors and currently only allows for partial identification. Historical compositions and a Mountford/Uhlig-style general identification will be contained in the next update.

**Comment by as4456** [comment]
Hi,
Thanks for explaining this.
Just referring to the above shared link  again, how do I give shock of interest of an exogenous shock.

In your example using uhligdata, when constructing the sign restriction vector, you have stated that
first element of constr indicates the shock of interest in the model. This shock is due to an endogenous variable (interest rate).

Also as a general usage example how would I pass constr for a 4 var and 4 shock system.

Thanks

**Comment by chrstdanne** [comment]
As mentioned above, full identification ala Mountford/Uhlig is currently not part of the package. You can, however, run the model 4 times and each time put a different shock first in constr=c(). But the shocks might not be fully orthogonal.
