### ISSUE TITLE
Doubt in FEVD

### ISSUE THREAD

**Issue by arnab13061989** [chrstdanne/VARsignR#5]
Dear Christian,

I have gone through your documentation . Could you please explain how your FEVD measure is different from the variance of the k step ahead forecast revision (as per fig 9 of Uhlig 2005) . You have mentioned the same in footnote 9 but it's not clear to me .  Could you kindly explain mathematically .

Regards
Arnab Biswas

**Comment by chrstdanne** [comment]
Hi Arnab, 

Uhlig (2005) explains reasonably well what he does. If you compare your box-standard FEVD computation with what he does it becomes quite clear. In essence, his procedure is a)  is a 'rolling' / 'updating' procedure. I think he uses 6 months windows over the span of 5 years to compute the forecast variances. The I hope that helps.
